program: src/ml_ops_project/train.py
method: bayes
metric:
  name: test_accuracy
  goal: maximize

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}

parameters:
  experiment.training.learning_rate:
    min: 0.0005
    max: 0.005
    distribution: log_uniform_values
  
  experiment.training.batch_size:
    values: [48, 64, 80, 96]
  
  experiment.training.epochs:
    values: [15, 20, 25, 30]

run_cap: 15

early_terminate:
  type: hyperband
  min_iter: 5