name: DVC Workflow

on:
  pull_request:
    branches:
      - main
    paths:
      - "**/*.dvc"
      - "dvc.lock"
      - "dvc.yaml"
      - ".dvc/**"

permissions:
  contents: read
  pull-requests: write

jobs:
  run_data_checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: uv sync

      - name: Auth with GCP
        uses: google-github-actions/auth@v3
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Pull data
        run: uv run dvc pull --no-run-cache

      - name: Check data statistics & generate report
        run: |
          uv run python src/ml_ops_project/dataset_stats_art.py --datadir data > data_statistics.md
          echo "" >> data_statistics.md
          echo "## Samples (AI-generated, label 0)" >> data_statistics.md
          echo '![](./art_samples_ai.png "AI samples")' >> data_statistics.md
          echo "" >> data_statistics.md
          echo "## Samples (Real art, label 1)" >> data_statistics.md
          echo '![](./art_samples_real.png "Real samples")' >> data_statistics.md
          echo "" >> data_statistics.md
          echo "## Label distribution" >> data_statistics.md
          echo '![](./art_label_distribution.png "Label distribution")' >> data_statistics.md
          echo "" >> data_statistics.md

      - name: Setup CML
        uses: iterative/setup-cml@v2

      - name: Comment on PR
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml comment create data_statistics.md --watermark-title="Data Checker"
